spring:
  application:
    name: sanad-spring-task
  datasource:
    url: jdbc:postgresql://localhost:5432/sanad
    username: sanaduser
    password: sanadpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
openexchangerates:
  app-id: 9156376d5a834a2fb5d01b89f24d98f5


